FROM lscr.io/linuxserver/beets:latest

COPY beets.config.yaml /config/config.yaml
COPY dist/importer/entrypoint.sh /usr/local/bin/groovarr-importer

RUN chmod +x /usr/local/bin/groovarr-importer

ENTRYPOINT ["/usr/local/bin/groovarr-importer"]
